# Generated by Django 3.2.7 on 2021-09-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_shipping_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='The iso currency code to use for payments', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='currency_html_code',
            field=models.CharField(blank=True, default='&pound;', help_text='The HTML code for the currency symbol. Used for display purposes only', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_carrier',
            field=models.CharField(blank=True, default='Royal Mail', help_text='The default shipping carrier', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.95, help_text='The default shipping rate for countries which have not been configured', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
